spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/excellence?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml